###############################################################
#                              Synopsis
# 
# 
# This Worflow will help deploy App and Infrastructure for POC
# 
# Created By : samuel.mamootil.ext@siemens.com
###############################################################
name: 'POC Env CI/CD'

on:
  workflow_dispatch:
  repository_dispatch:
    types: [feature/terraform]
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - feature/terraform
  push:
    branches:
      - feature/terraform
      
jobs:
  #Deploy Infrasturcture using Terraform 
  deploy-poc-env:
    name: POC
    # if: github.ref == 'refs/heads/main'
    uses: samuelmamootil/kpmg-tech-challenge/.github/workflows/terraform.yml@main
    with:
      env_name: poc
      env_path: cicd/tf/envs/dev
    secrets: inherit
